// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class DETALLE_FACTURA
{
    public int id_detalle_factura { get; set; }

    public int? id_factura { get; set; }

    public int? id_vehiculo { get; set; }

    public DateTime? fecha_entrada { get; set; }

    public DateTime? fecha_salida { get; set; }

    public string id_lugar { get; set; }

    public int? id_abono { get; set; }

    public decimal? precio { get; set; }

    public decimal? descuento { get; set; }

    public decimal? recargo { get; set; }

    public virtual ABONO id_abonoNavigation { get; set; }

    public virtual FACTURA id_facturaNavigation { get; set; }

    public virtual LUGARE id_lugarNavigation { get; set; }

    public virtual VEHICULO id_vehiculoNavigation { get; set; }
}